name: "Excerice 1 github action"
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]  
jobs:
  checkout-branche:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

  install-dependeces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          pip install pipenv
          pipenv --python 3.8
          pipenv install nose pylint --dev
      - name: launch lint on app
        run:  pipenv run pylint app

      - name: Launch test
        run: pipenv run nosetests
          