name: "Excerice 1 github action"
on: [push, pull_request]
jobs:
  checkout-branche:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

  workflow-jobs-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Installing dependences
        run: |
          pip install pipenv
          pipenv --python 3.8
          pipenv install nose pylint --dev

      - name: launch lint on app
        run:  pipenv run pylint app

      - name: Launch test
        run: pipenv run nosetests

  review:
    if: ${{ github.ref != 'refs/head/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: My first auto PR
          title: Awesome PR by ${{ github.actor }}
          body: |
            Test de création de PR grâce a github action

            Branche en cours ${{ github.ref }}

          branch: ${{ github.ref }}  



          